---
title: "WINK taxonomic report"
output: 
  html_document
params:
  n: NA
  brackenData: NA
  total_barcodes: NA
  total_reads: NA
  ass_reads: NA
  run_time: NA
---

*Generated with the [WINK analysis pipeline](https://github.com/angelovangel/wink.git) on `r Sys.time()`*

#### Run and taxonomic assignment summary

|                |  |
|----------------|--|
| Total barcodes: | `r params$total_barcodes` |
|    Total reads: | `r params$total_reads` |
| Assigned reads: | `r params$ass_reads` |
|       Run time: | `r params$run_time` |



```{r, include=FALSE}
# setup shared data object
# all data input is from brackenData()
require(dplyr)
require(DT)
```

#### Taxonomic assignments and abundance estimation per sample

```{r, include=TRUE, eval=TRUE, echo=FALSE}

taxdb_left = "https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id="
taxdb_right = "&lvl=3&lin=f&keep=1&srchmode=1&unlock"

df <- params$brackenData %>%
	dplyr::mutate(
				taxonomyID = paste0(taxdb_left, taxonomy_id, taxdb_right), #two-step mutate to build href
				kraken_reads = kraken_assigned_reads,
				bracken_corr_reads = new_est_reads, 
				freq = round(freq*100, 2)
				) %>% 
	dplyr::filter(name != "unclassified") %>%
	dplyr::mutate(
				taxonomyID = paste0("<a target = '_blank' href='", taxonomyID, "'>", taxonomy_id, "</a>")
				) %>%
	dplyr::select(file, name, taxonomyID, kraken_reads, bracken_corr_reads, freq)

datatable(
  df,
  escape = FALSE,
  selection = "none",
  caption = "Bracken abundance table",
  filter = 'top', 
  rownames = FALSE, 
  class = 'hover row-border',
  options = list(dom = 'Prtip', 
  							 searchPanes = list(cascadePanes = TRUE),
  							 columnDefs = list(
  							 	list(
  							 		searchPanes = list(show = FALSE), targets = 2:5
  							 		)
  							 	)),
  extensions = c('Select', 'SearchPanes')
)

```
